include build/make/target/board/generic_arm64_ab/BoardConfig.mk

TARGET_COPY_OUT_VENDOR := vendor
# ~350M
BOARD_VENDORIMAGE_PARTITION_SIZE := 367001600
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# ~1.3G
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1388314624

BOARD_BUILD_SYSTEM_ROOT_IMAGE := true

TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

BOARD_GPU_DRIVERS := virgl radeonsi

DEVICE_MANIFEST_FILE += device/redroid/manifest.xml

